### ISSUE TITLE
Undefined name 'x' in mask_rcnn_heads.py

### ISSUE THREAD

**Issue by cclauss** [ShuLiu1993/PANet#1]
flake8 testing of https://github.com/ShuLiu1993/PANet on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/modeling/mask_rcnn_heads.py:62:16: F821 undefined name 'x'
        return x
               ^
1     F821 undefined name 'x'
1
```

**Comment by ShuLiu1993** [comment]
Corrected. Thanks a lot for your feedback!

**Comment by cclauss** [comment]
Nice work!
