### ISSUE TITLE
Multiple batch images inference

### ISSUE THREAD

**Issue by SeokjuLee** [ShuLiu1993/PANet#12]
Hi Shu, thanks for sharing the code!

I want to ask how to implement multi-GPU/batch inference on your code.
Could you give me some advice to easily implement it?

**Comment by chelixuan** [comment]
use command:
python tools/test_net.py --dataset coco2017 --cfg configs/panet/e2e_panet_R-50-FPN_2x_mask.yaml --load_ckpt {path/to/your/checkpoint} --multi-gpu-testing

it works well for me. hope can help you~ @SeokjuLee

**Comment by SeokjuLee** [comment]
@chelixuan Hi Chelixuan, thanks for your reply!
