### ISSUE TITLE
Can this implementation handle images without objects?

### ISSUE THREAD

**Issue by SingL3** [ShuLiu1993/PANet#17]
Hello!
I want to train a model with some samples that has no objects ( just background ).
Can this implementation handle that?

**Comment by ShuLiu1993** [comment]
Maybe you can simply filter those images out for training. For inference, it will be okay.

**Comment by SingL3** [comment]
Actually, I have modified it to accept these images and now I am testing it.

**Comment by ShuLiu1993** [comment]
Great to know that!

**Comment by akshitac8** [comment]
@SingL3 How did you modified it for accepting images without objects.

**Comment by SingL3** [comment]
@akshitac8 you will have to modify the data loading and the label assignment part of anchor and roi.

**Comment by akshitac8** [comment]
Can you state some more details plz? Because I didn't change anything in the code and still it was able to process the images(without objects) from my dataset.
