### ISSUE TITLE
License

### ISSUE THREAD

**Issue by allansp84** [ShuLiu1993/PANet#26]
Hi Dear,
Could you tell me what is the license of this software, please?
According to _GitHub's Policy_, all repositories without an explicit license are considered Copyrighted materials. Do the authors intend to make this software free?
Thank you!

**Comment by ShuLiu1993** [comment]
Hi, I have added the MIT license. Enjoy!

**Comment by allansp84** [comment]
Thank you so much, Mr. Shu!
