### ISSUE TITLE
Question about  the demo?

### ISSUE THREAD

**Issue by zhangxgu** [ShuLiu1993/PANet#6]
Hi, how can I run a demo only for a file with images and no annotations? I find that the function 

> run_inference()

 in test_engine.py  need json file for the dataset, but in my situation I only want to show the segmentation results of a few local figures.
Hope you can help! Thank you!

**Comment by zhangxgu** [comment]
@ShuLiu1993

**Comment by ash1995** [comment]
How were you able to run inference on images without the annotations?
