### ISSUE TITLE
Training on Cityscapes

### ISSUE THREAD

**Issue by davidchuyaya** [ShuLiu1993/PANet#8]
Are these the only lines (in [train_net_step.py](https://github.com/ShuLiu1993/PANet/blob/master/tools/train_net_step.py)) that need to be changed to train on Cityscapes?

```python
     if args.dataset == "coco2017":
        cfg.TRAIN.DATASETS = ('coco_2017_train',)
        cfg.MODEL.NUM_CLASSES = 81
    elif args.dataset == "keypoints_coco2017":
        cfg.TRAIN.DATASETS = ('keypoints_coco_2017_train',)
        cfg.MODEL.NUM_CLASSES = 2
    else:
        raise ValueError("Unexpected args.dataset: {}".format(args.dataset))
```

**Comment by ShuLiu1993** [comment]
No, you need to write your own data processing interface to read the annotation from Cityscapes etc.

**Comment by EliasVansteenkiste** [comment]
@davidchuyaya Did you ever manage to train on Cityscapes?
