### ISSUE TITLE
training slowly

### ISSUE THREAD

**Issue by cltdevelop** [ShuLiu1993/PANet#9]
Wonderful works!
Thank you for sharing your code!

It took about 30 seconds when I trained 20 steps with four Titan X GPU.  So can you give me some suggestions to speed up training process? Thank you in advance.

**Comment by ShuLiu1993** [comment]
Thanks a lot for your interest!

I used 8 * P40 for training. Maybe the best way is to use more GPU cards...

**Comment by cltdevelop** [comment]
OK, thank you
